### ISSUE TITLE
解除仅手环可以用于蓝牙解锁的限制

### ISSUE THREAD

**Issue by tonynesss** [zixing131/mibluetoothunlocker#1]
能否破解可以用于解锁的设备限制呢，主要可以用于平板上，让手机可用于蓝牙设备的解锁的功能，当手机在平板附近时可自动解锁平板。

**Comment by zixing131** [comment]
参考此贴评论区内容
https://www.coolapk.com/feed/17074161?shareKey=NjhlNDIzODBmMWQ4NjMyNThkMmI~&shareUid=719351&shareFrom=com.coolapk.market_12.4.3

**Comment by zixing131** [comment]
手机用于解锁的话，可能要保持手机蓝牙一直可被发现才行，或者手机和平板配对然后进行连接，具体我后面测试一下

**Comment by tonynesss** [comment]
> 手机用于解锁的话，可能要保持手机蓝牙一直可被发现才行，或者手机和平板配对然后进行连接，具体我后面测试一下

手机的蓝牙支持蓝牙低功耗模式，蓝牙的mac地址都是随机可变的。这可能是个问题。但若同为小米的手机和平板，或许可以参考小米miui+的设备互联。无需保持蓝牙始终连接也可进行数据传输

**Comment by tonynesss** [comment]
> 手机用于解锁的话，可能要保持手机蓝牙一直可被发现才行，或者手机和平板配对然后进行连接，具体我后面测试一下

昨天试了一下，突然发现可以使用手机作为解锁设备了，不需要保持始终连接，也不需要依托miui＋，甚至比连接手环的情况更加灵敏更好用。解锁信号阈值的设置也可以生效。但是信号阈值的设置似乎有些问题，设置为0但依然可以在较远距离解锁。

**Comment by zixing131** [comment]
这个是因为信号获取不到，你看一下lsposed的日志，信号可能获取到的是缓存的信号值或者是固定的一个数值

**Comment by tonynesss** [comment]
刚看了下日志，信号是会随着距离不同而改变的，但是不会像手环设备改变的那么大，基本稳定在-10以内，手环设备靠近的话信号强度可以-50左右，手机的可以直接到0[Screenshot_2022-09-23-09-36-53-655_bin.mt.plus.png](https://user-images.githubusercontent.com/32998682/191878033-55772c53-aa91-4fb1-aefe-44d1f4571533.png)

**Comment by zixing131** [comment]
那信号太强了也没办法

**Comment by tonynesss** [comment]
还是可以用的，就是不太稳定。不知道是不是因为同为小米设备的特殊加成，其他的手机还没有试过。😂

**Comment by zixing131** [comment]
后期打算改成直接在软件里面加设备，不用系统设置里面的添加了，这样可以添加多个设备用于解锁，并且可以给每个设备设置单独的阈值。
（再后期可能有免root模式和蓝牙触发器功能，设定一个蓝牙mac地址和需要触发的操作，然后发现设备或者远离设备的时候进行触发，不过这些功能可能要再等亿年吧）

**Comment by zixing131** [comment]
3.5版本已经更新

**Comment by tonynesss** [comment]
> 3.5版本已经更新

测试可用，建议版本直接跳4.0。😍

**Comment by zixing131** [comment]
> 
先观望一下，如果没啥bug的话，我其实也不想做改动了，毕竟我需要的功能都已经实现了
